return {
	{
		"folke/which-key.nvim",
		event = "VeryLazy",
		init = function()
			vim.g.which_key_delay = 1000
		end,
		opts = {
			icons = {
				keys = {
					Up = "<Up>",
					Down = "<Down>",
					Left = "<Left>",
					Right = "<Right>",
					C = "<C-…>",
					M = "<M-…>",
					D = "<D-…>",
					S = "<S-…>",
					CR = "<CR>",
					Esc = "<Esc>",
					ScrollWheelUp = "<ScrollWheelUp>",
					ScrollWheelDown = "<ScrollWheelDown>",
					BSP = "<BS>",
					Tab = "<Tab>",
					F1 = "<F1>",
					F2 = "<F2>",
					F3 = "<F3>",
					F4 = "<F4>",
					F5 = "<F5>",
					F6 = "<F6>",
					F7 = "<F7>",
					F8 = "<F8>",
					F9 = "<F9>",
					F10 = "<F10>",
					F11 = "<F11>",
					F12 = "<F12>",
				},
			},
			spec = {
				{ mode = "n" },
				{ "<leader>c", group = "code" },
				{ "<leader>d", group = "debug / db" },
				{ "<leader>f", group = "find" },
				{ "<leader>g", group = "git" },
				{ "<leader>h", group = "highlight" },
				{ "<leader>l", group = "lsp" },
				{ "<leader>o", group = "outline" },
				{ "<leader>t", group = "tests" },
				{ "<leader>R", group = "http requests" },
				{ "<leader>k", group = "sidekick" },
				{ "<C-n>", group = "neo-tree" },
				{ "<C-p>", group = "telescope" },
				{ "<leader><leader>", group = "old files" },
			},
		},
	},
}
